window.albumCoverMap = {
  "album|100种生活|卢广仲": "covers/10072.jpg",
  "album|15|方大同": "covers/10136.jpg",
  "album|2014 forest hills drive|j. cole": "covers/10009.jpg",
  "album|ambient 1: music for airports|brian eno": "covers/10149.jpg",
  "album|beauty behind the madness|the weeknd": "covers/10046.jpg",
  "album|brothers & sisters|soil & “pimp” sessions": "covers/10035.jpg",
  "album|bttb|坂本龙一": "covers/10016.jpg",
  "album|chinese football|chinese football": "covers/10075.jpg",
  "album|chromakopia|tyler, the creator": "covers/10092.jpg",
  "album|confield|autechre": "covers/10103.jpg",
  "album|cosmogramma|flying lotus": "covers/10157.jpg",
  "album|ctrl|sza": "covers/10021.jpg",
  "album|currents|tame impala": "covers/10066.jpg",
  "album|death stranding (songs from the video game)|various artists": "covers/10130.jpg",
  "album|discovery|daft punk": "covers/2.jpg",
  "album|donda|kanye west": "covers/10005.jpg",
  "album|dots and loops|stereolab": "covers/10153.jpg",
  "album|essex honey|blood orange": "covers/10106.jpg",
  "album|fragile|yes": "covers/10127.jpg",
  "album|funeral|arcade fire": "covers/10089.jpg",
  "album|ghosts from the past|bang gang": "covers/10178.jpg",
  "album|good kid, m.a.a.d city|kendrick lamar": "covers/10022.jpg",
  "album|grace|jeff buckley": "covers/10154.jpg",
  "album|graduation|kanye west": "covers/10047.jpg",
  "album|i'm ok|陶喆": "covers/10055.jpg",
  "album|illmatic|nas": "covers/10001.jpg",
  "album|in rainbows|radiohead": "covers/10048.jpg",
  "album|in the court of the crimson king|king crimson": "covers/10094.jpg",
  "album|invincible|michael jackson": "covers/10051.jpg",
  "album|jesus is king|kanye west": "covers/10003.jpg",
  "album|kid a|radiohead": "covers/10061.jpg",
  "album|lahai|sampha": "covers/10042.jpg",
  "album|long season|fishmans": "covers/10045.jpg",
  "album|luv(sic) hexalogy|nujabes & shing02": "covers/10014.jpg",
  "album|madvillainy|madvillain": "covers/10027.jpg",
  "album|metaphorical music|nujabes": "covers/10018.jpg",
  "album|michael|michael jackson": "covers/10052.jpg",
  "album|music for nine post cards|吉村弘": "covers/10148.jpg",
  "album|my beautiful dark twisted fantasy|kanye west": "covers/10002.jpg",
  "album|null & void|ground-zero": "covers/10179.jpg",
  "album|opus|坂本龙一": "covers/10087.jpg",
  "album|origin of symmetry|muse": "covers/10135.jpg",
  "album|our waning love|谢明谚": "covers/10123.jpg",
  "album|playing the piano|坂本龙一": "covers/10069.jpg",
  "album|portable audio science|honeydip": "covers/10091.jpg",
  "album|purple rain|prince and the revolution": "covers/10067.jpg",
  "album|random access memories|daft punk": "covers/10065.jpg",
  "album|re:re:re:|惘闻": "covers/10077.jpg",
  "album|re|café tacvba": "covers/10176.jpg",
  "album|rumours|fleetwood mac": "covers/10152.jpg",
  "album|since i left you|the avalanches": "covers/10142.jpg",
  "album|son of spergy|daniel caesar": "covers/10116.jpg",
  "album|songs in the key of life|stevie wonder": "covers/10058.jpg",
  "album|stankonia|outkast": "covers/10150.jpg",
  "album|starship syncopation|cory wong, metropole orkest & jules buckley": "covers/10104.jpg",
  "album|taxi driver|bernard herrmann": "covers/10134.jpg",
  "album|the epic|kamasi washington": "covers/10132.jpg",
  "album|the life of pablo|kanye west": "covers/10004.jpg",
  "album|the miseducation of lauryn hill|lauryn hill": "covers/10033.jpg",
  "album|the now now and never|what is your name?": "covers/10088.jpg",
  "album|three|坂本龙一": "covers/10037.jpg",
  "album|thriller|michael jackson": "covers/10068.jpg",
  "album|thunder, lightning, strike|the go! team": "covers/10163.jpg",
  "album|tnt|tortoise": "covers/10171.jpg",
  "album|to pimp a butterfly|kendrick lamar": "covers/10008.jpg",
  "album|velocity: design: comfort.|sweet trip": "covers/10036.jpg",
  "album|voodoo|d'angelo": "covers/10160.jpg",
  "album|vultures 1|¥$ (kanye west & ty dolla $ign)": "covers/10085.jpg",
  "album|vultures 2|¥$ (kanye west & ty dolla $ign)": "covers/10086.jpg",
  "album|we will always love you|the avalanches": "covers/4.jpg",
  "album|wish you were here|pink floyd": "covers/10115.jpg",
  "album|wolfgang amadeus phoenix|phoenix": "covers/10155.jpg",
  "album|yellow magic orchestra|yellow magic orchestra": "covers/10031.jpg",
  "album|この道の向こうに|巨勢典子": "covers/10090.jpg",
  "album|万能青年旅店|万能青年旅店": "covers/10095.jpg",
  "album|乐典：侗族（叁）|乐典 & 黔东南侗族原住民": "covers/10126.jpg",
  "album|冀西南林路行|万能青年旅店": "covers/10093.jpg",
  "album|卡拉ok.台北.我|张雨生": "covers/10131.jpg",
  "album|只爱陌生人|王菲": "covers/10071.jpg",
  "album|宋岳庭的羽毛|宋岳庭": "covers/10117.jpg",
  "album|巴蜀文艺复兴：第二章|施鑫文月": "covers/10028.jpg",
  "album|幽默与笑话|卡力老虎 & jesse margiela": "covers/10113.jpg",
  "album|敬！李双泽 唱自己的歌|群星": "covers/10124.jpg",
  "album|新长征路上的摇滚|崔健": "covers/10121.jpg",
  "album|月下世界|天鹅与花朵": "covers/10128.jpg",
  "album|枯萎颂|王忆灵": "covers/10138.jpg",
  "album|橙月|方大同": "covers/10073.jpg",
  "album|浮躁|王菲": "covers/10175.jpg",
  "album|渋夜旅|渋さ知らズ": "covers/10143.jpg",
  "album|看不见的城市|惘闻": "covers/10081.jpg",
  "album|菊花夜行军|交工乐队": "covers/10110.jpg",
  "album|蝴蝶的罪恶感|po8": "covers/10049.jpg",
  "album|非想非非想|王蓉": "covers/10147.jpg"
};
