window.filmSeedEntries = [
  {
    id: 30001,
    type: "film",
    title: "凶线",
    subtitle: "Blow Out",
    creator: "布莱恩·德·帕尔玛",
    releaseYear: 1981,
    rating: null,
    loggedDate: "2026-09-05",
    summary: "前面一直没真正击中我，直到最后一声尖叫把整部电影突然钉死。",
    note: "真实死亡被剪进虚构电影，职业、技术、感情与失败最后压进同一段声音里。",
    tags: "声音,媒介,阴谋,悲剧",
    favorite: false,
    accent: "blue",
    image: ""
  },
  {
    id: 30002,
    type: "film",
    title: "诗",
    subtitle: "시 / Poetry",
    creator: "李沧东",
    releaseYear: 2010,
    rating: null,
    loggedDate: "2026-09-10",
    note: "",
    tags: "韩国,诗歌,记忆,伦理",
    favorite: false,
    accent: "green",
    image: ""
  }
];

window.filmSeedEntries.push({
  "id": 30003,
  "type": "film",
  "title": "空房间",
  "subtitle": "3-Iron",
  "creator": "金基德",
  "releaseYear": 2004,
  "rating": null,
  "loggedDate": "2026-10-01",
  "status": "wishlist",
  "summary": "一个借住空屋的青年，与一位沉默的女人结伴进入陌生人的生活。",
  "note": "",
  "tags": "韩国,爱情,沉默",
  "favorite": false,
  "accent": "red",
  "image": ""
});

window.filmSeedEntries.push(
  {
    "id": 30004,
    "type": "film",
    "title": "绿鱼",
    "subtitle": "초록물고기 / Green Fish",
    "creator": "李沧东",
    "releaseYear": 1997,
    "rating": null,
    "loggedDate": "2026-10-02",
    "status": "wishlist",
    "summary": "一个退伍青年卷入黑帮世界，在城市变化中寻找自己的位置。",
    "note": "李沧东长片处女作。",
    "tags": "韩国,社会,黑帮",
    "favorite": false,
    "accent": "green",
    "image": ""
  },
  {
    "id": 30005,
    "type": "film",
    "title": "薄荷糖",
    "subtitle": "박하사탕 / Peppermint Candy",
    "creator": "李沧东",
    "releaseYear": 2000,
    "rating": null,
    "loggedDate": "2026-10-02",
    "status": "wishlist",
    "summary": "一个男人在生命终点回望自己被时代逐渐改变的一生。",
    "note": "",
    "tags": "韩国,时间,记忆,时代",
    "favorite": false,
    "accent": "green",
    "image": ""
  },
  {
    "id": 30006,
    "type": "film",
    "title": "绿洲",
    "subtitle": "오아시스 / Oasis",
    "creator": "李沧东",
    "releaseYear": 2002,
    "rating": null,
    "loggedDate": "2026-10-02",
    "status": "wishlist",
    "summary": "两个被社会边缘化的人，在误解与排斥中寻找彼此。",
    "note": "",
    "tags": "韩国,爱情,边缘人",
    "favorite": false,
    "accent": "green",
    "image": ""
  },
  {
    "id": 30007,
    "type": "film",
    "title": "密阳",
    "subtitle": "밀양 / Secret Sunshine",
    "creator": "李沧东",
    "releaseYear": 2007,
    "rating": null,
    "loggedDate": "2026-10-02",
    "status": "wishlist",
    "summary": "一名失去至亲的女性，在痛苦、信仰与宽恕之间寻找出口。",
    "note": "",
    "tags": "韩国,信仰,痛苦,救赎",
    "favorite": false,
    "accent": "green",
    "image": ""
  }
);
